# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MPCamera
  pod 'GPUImage'
  pod 'Masonry'
  pod 'RSSwizzle'
  pod 'Toast', '~> 4.0.0'

  target 'MPCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MPCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
